### ISSUE TITLE
Can't create mix with numeric title

### ISSUE THREAD

**Issue by alexandersimoes** [alexandersimoes/mixtur#18]
For instance creating a mix with the title '1' or '69' or '999999999' raises errors. Bug found thx to @charleszardo.

**Comment by alexandersimoes** [comment]
Seems sqlite3 doesn't respect schema types and will treat a number held in a string column as an int. Arghhhhhhh!!!

**Comment by charleszardo** [comment]
what about '420'?  or Phở-20....?

**Comment by alexandersimoes** [comment]
It's fixed now, I explicitly wrap everything I get from the db in a [unicode()](https://docs.python.org/2/library/functions.html#unicode) call. Also Phở-20 would have always worked (string+numeric is fine) but 420 would have caused that same issue :herb: :wink:
