### ISSUE TITLE
Editing/Uploading not working properly

### ISSUE THREAD

**Issue by charleszardo** [alexandersimoes/mixtur#19]
While uploading, there were no signs of anything going wrong until I took a look at the mix.  Photo didn't upload and title/artist weren't saved after the first track.  Tried to edit the mix and I'm getting werkzeug.routing.BuildError

**Comment by alexandersimoes** [comment]
Hmm wasn't able to reproduce this. Could you post the song(s)/image you were trying to upload as well the exact title/description you used.

**Comment by charleszardo** [comment]
Did you try editing a mix?  If you can't reproduce it with any of your mixes, I'll give you my creds.  It's still happening with the most recent mix I tried to add (II).

**Comment by alexandersimoes** [comment]
Oh w00000ps sorry it's when you EDIT a mix you've already created. OK i'll
look into this.

**Comment by charleszardo** [comment]
I'm a fool - I made a new mix and deleted the one where the issue was occurring.  New mix worked at least.  Closing issue for now.  Will reopen if observed again.
